global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/mono/finance-app/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7500']