
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod(operationName = "ListComptes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListComptes", targetNamespace = "http://ws/", className = "ws.ListComptes")
    @ResponseWrapper(localName = "ListComptesResponse", targetNamespace = "http://ws/", className = "ws.ListComptesResponse")
    @Action(input = "http://ws/BanqueService/ListComptesRequest", output = "http://ws/BanqueService/ListComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param code
     * @return
     *     returns ws.Compte
     */
    @WebMethod(operationName = "GetCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "GetCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/GetCompteRequest", output = "http://ws/BanqueService/GetCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToLBP")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToLBP", targetNamespace = "http://ws/", className = "ws.ConversionEuroToLBP")
    @ResponseWrapper(localName = "ConversionEuroToLBPResponse", targetNamespace = "http://ws/", className = "ws.ConversionEuroToLBPResponse")
    @Action(input = "http://ws/BanqueService/ConversionEuroToLBPRequest", output = "http://ws/BanqueService/ConversionEuroToLBPResponse")
    public double conversionEuroToLBP(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
