apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: micro-app
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8093          # External port for accessing the service
      targetPort: 8093  # Internal container port
      nodePort: 31293
  type: NodePort
