apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8090          # External port for accessing the service
      targetPort: 8090  # Internal container port
  type: ClusterIP       # Internal service for communication within the cluster
