apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: micro-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8090          # External port for accessing the service
      targetPort: 8090  # Internal container port
      nodePort: 31290
  type: NodePort       # Internal service for communication within the cluster
