apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
  namespace: micro-app
  labels:
    app: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: client-service
    spec:
      #hostNetwork: true
      containers:
        - name: client-service
          image: localhost:5000/client-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          resources:
            requests:
              memory: "512Mi"
              cpu: "750m"
            limits:
              memory: "1Gi"
              cpu: "2"
          env:
            # Database configuration
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5433/mono-db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          readinessProbe:
            httpGet:
              path: /micro/client-service/actuator/health
              port: 8091
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /micro/client-service/actuator/health
              port: 8091
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
