apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-service-hpa
  namespace: micro-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-service-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
