apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: micro-app
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8091          # External port for accessing the service
      targetPort: 8091  # Internal container port
      nodePort: 31291
  type: NodePort       # Internal service for communication within the cluster
