apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8091          # External port for accessing the service
      targetPort: 8091  # Internal container port
  type: ClusterIP       # Internal service for communication within the cluster
