apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: micro-app
data:
  pgbouncer.ini: |
    [databases]
    mono-db = host=<external-db-host> port=5433 dbname=mono-db

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = trust  
    max_client_conn = 500  
    default_pool_size = 80  
    reserve_pool_size = 10  
    reserve_pool_timeout = 5  
    pool_mode = transaction 
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    ignore_startup_parameters = extra_float_digits
