apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: micro-app
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 31295
  clusterIP: 10.105.237.85
  type: NodePort
