apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: micro-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: micro-app
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespace: micro-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-role
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: micro-app
