apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service-deployment
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: localhost:5000/micro-report-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          resources:
            requests:
              cpu: "100m"       # Minimum CPU: 10% of a core
              memory: "128Mi"   # Minimum memory: 128MiB
            limits:
              cpu: "200m"       # Maximum CPU: 20% of a core
              memory: "256Mi"   # Maximum memory: 256MiB
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 15
            periodSeconds: 10
