apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: micro-app
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8092          # External port for accessing the service
      targetPort: 8092  # Internal container port
      nodePort: 31292
  type: NodePort       # Internal service for communication within the cluster
