apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: micro-app
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8094          # External port for accessing the service
      targetPort: 8094  # Internal container port
      nodePort: 31294
  type: NodePort       # Internal service for communication within the cluster
  sessionAffinity: None   # Ensure traffic is distributed evenly across pods

