apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80          # External port for accessing the service
      targetPort: 8094  # Internal container port
  type: ClusterIP       # Internal service for communication within the cluster
