apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  namespace: micro-app
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      #hostNetwork: true
      containers:
        - name: transaction-service
          image: localhost:5000/transaction-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8094
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            # Database configuration
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5433/mono-db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          readinessProbe:
            httpGet:
              path: /micro/transaction-service/actuator/health
              port: 8094
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /micro/transaction-service/actuator/health
              port: 8094
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
