apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-service-hpa
  namespace: micro-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-service-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # Wait 60 seconds before scaling up further
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10 # Add 1 pod at most every 30 seconds
    scaleDown:
      stabilizationWindowSeconds: 300 # Prevent aggressive scale-down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # Remove 1 pod at most every 60 seconds